.gitignore
README.md

#1 Add PRD skeleton

---

README.md

#1 Entities, User rights, REST API proposed

#1 Update with Domain model & API prototype

---

README.md

Restructure PRD

---

README.md

#1 Provide some alternatives to PRD

---

README.md

#1 Fix formatting

---

README.md

# Improve PRD readability

---

README.md

#1 PRD minor changes

---

samples/input_form.html

#11 Create sample input form

---

pom.xml
src/main/java/io/github/externschool/planner/config/SpringSecurityConfig.java

18:dependencies added and security config created

---

src/main/java/io/github/externschool/planner/entity/User.java
src/main/java/io/github/externschool/planner/repository/UserRepository.java
src/main/resources/application.properties

connect to #22 
Simple user entity, user repository added
h2 application properties added
could not launch h2-console, any request is redirected to "/login" page with "Whitelabel Error Page"

22: Create Simple User Entity

---

src/main/java/io/github/externschool/planner/service/UserService.java
src/main/java/io/github/externschool/planner/service/UserServiceImpl.java

connect to #23 
userService created

#23: user service interface and implementation created

---

src/main/java/io/github/externschool/planner/entity/User.java
src/main/java/io/github/externschool/planner/entity/profile/Gender.java
src/main/java/io/github/externschool/planner/entity/profile/Person.java
src/main/java/io/github/externschool/planner/entity/profile/Student.java
src/main/java/io/github/externschool/planner/entity/profile/Teacher.java
src/main/java/io/github/externschool/planner/repository/profiles/GuestRepository.java
src/main/java/io/github/externschool/planner/repository/profiles/StudentRepository.java
src/main/java/io/github/externschool/planner/repository/profiles/TeacherRepository.java

Mnjl1 50 add user profile tree

---

src/main/java/io/github/externschool/planner/entity/Authority.java
src/main/java/io/github/externschool/planner/entity/User.java
src/main/resources/db/changelog/db.changelog-1.0.xml
src/main/resources/db/changelog/db.changelog-2.0.xml
src/main/resources/db/changelog/db.changelog-master.xml

Connect #47 
Add relation between User and Authority. Use many-to-many relation type. And changed db.changelog-master.xml.

47 add relation beetwen user and authority

---

.gitignore
src/main/java/io/github/externschool/planner/config/SpringSecurityConfig.java
src/main/java/io/github/externschool/planner/dto/UserDTO.java
src/main/java/io/github/externschool/planner/entity/Role.java
src/main/java/io/github/externschool/planner/entity/User.java
src/main/java/io/github/externschool/planner/repository/RoleRepository.java
src/main/java/io/github/externschool/planner/repository/UserRepository.java
src/main/resources/db/changelog/db.changelog-1.0.xml
src/main/resources/db/changelog/db.changelog-2.0.xml
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java
src/test/java/io/github/externschool/planner/repository/RoleRepositoryIntegrationTest.java
src/test/java/io/github/externschool/planner/repository/UserRepositoryIntegrationTest.java

#62 Refactor user-authorities

---

pom.xml
src/main/java/io/github/externschool/planner/aop/LoggingAspect.java

Add new Class  LoggingAspect with  3 aspects (@Before, @Around,   @After) and add in pom dependency

#51 Add debug logging settings

---

src/main/java/io/github/externschool/planner/entity/SchoolSubject.java
src/main/java/io/github/externschool/planner/entity/TeacherSubject.java
src/main/java/io/github/externschool/planner/entity/profile/Student.java
src/main/java/io/github/externschool/planner/entity/profile/Teacher.java
src/main/java/io/github/externschool/planner/repository/profiles/PersonRepository.java
src/main/java/io/github/externschool/planner/repository/profiles/StudentRepository.java
src/test/java/io/github/externschool/planner/repository/profiles/PersonRepositoryTest.java
src/test/java/io/github/externschool/planner/repository/profiles/StudentRepositoryTest.java

connect to #57 
tests added, but ...
Teacher class is still commented, 'cause Subject class  is not created (out of task scope).

ticket to #57, tests added

---

src/main/java/io/github/externschool/planner/entity/User.java
src/main/java/io/github/externschool/planner/entity/schedule/ScheduleEvent.java
src/main/java/io/github/externschool/planner/entity/schedule/ScheduleEventType.java
src/main/java/io/github/externschool/planner/repository/schedule/ScheduleEventRepository.java
src/main/java/io/github/externschool/planner/repository/schedule/ScheduleEventTypeRepository.java
src/test/java/io/github/externschool/planner/factories/UserFactory.java
src/test/java/io/github/externschool/planner/factories/schedule/ScheduleEventFactory.java
src/test/java/io/github/externschool/planner/factories/schedule/ScheduleEventTypeFactory.java
src/test/java/io/github/externschool/planner/repository/schedule/ScheduleEventRepositoryIntegrationTest.java
src/test/java/io/github/externschool/planner/repository/schedule/ScheduleEventTypeRepositoryIntegrationTest.java
src/test/resources/datasets/scheduleEvent/oneEvent.sql
src/test/resources/datasets/scheduleEventType/oneType.sql
src/test/resources/datasets/user/oneUser.sql

connect to #64 
Added simple version of  entities and repositories for they

64 add entities event and type event

---

src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/test/java/io/github/externschool/planner/service/UserServiceTest.java

Connect #49 added default role (GUEST) for each new user.
Changed UserServiceImpl and UserServiceTest.

#49 added default role (GUEST) for each new user.

---

src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/main/resources/db/changelog/db.changelog-2.0.xml
src/test/java/io/github/externschool/planner/repository/RoleRepositoryIntegrationTest.java

Reverts ExternSchool/planner#87

Revert "#86 Fix Roles adding ROLE_ prefix to DB stored role names"

---

src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/main/resources/db/changelog/db.changelog-2.0.xml
src/test/java/io/github/externschool/planner/repository/RoleRepositoryIntegrationTest.java

#86 restore accidentally reverted commit

---

src/main/resources/templates/teacher/teacher_profile.html

#81 Teacher Profile Template

---

src/main/java/io/github/externschool/planner/controller/TeacherController.java

#80 Added Teacher Controller

---

src/main/java/io/github/externschool/planner/entity/profile/Person.java
src/main/java/io/github/externschool/planner/entity/profile/Student.java
src/main/java/io/github/externschool/planner/entity/profile/Teacher.java
src/main/resources/templates/teacher/teacher_profile.html

#99 Fix verification key usage

---

src/main/java/io/github/externschool/planner/dto/TeacherDTO.java

77-teacher dto cteated

---

pom.xml

#92 Fix pom.xml: slf4j & logback dependencies

#92 Fix pom.xml: slf4j & logback dependencies

---

src/main/java/io/github/externschool/planner/entity/profile/Teacher.java
src/main/java/io/github/externschool/planner/repository/profiles/TeacherRepository.java
src/main/java/io/github/externschool/planner/service/TeacherService.java
src/main/java/io/github/externschool/planner/service/TeacherServiceImpl.java
src/test/java/io/github/externschool/planner/repository/profiles/TeacherRepositoryTest.java
src/test/java/io/github/externschool/planner/service/TeacherServiceTest.java

#79 Add TeacherService

---

src/main/resources/templates/subject/subject_list.html

#108 create template for school subjects

---

src/main/java/io/github/externschool/planner/entity/SchoolSubject.java
src/main/java/io/github/externschool/planner/repository/SchoolSubjectRepository.java
src/main/java/io/github/externschool/planner/service/SchoolSubjectService.java
src/main/java/io/github/externschool/planner/service/SchoolSubjectServiceImpl.java
src/test/java/io/github/externschool/planner/repository/SchoolSubjectRepositoryIntegrationTest.java
src/test/java/io/github/externschool/planner/repository/profiles/SchoolSubjectRepositoryTest.java
src/test/java/io/github/externschool/planner/service/SchoolSubjectServiceTest.java

107 Create SchoolSubject Service

---

src/main/java/io/github/externschool/planner/converter/TeacherDTOToTeacher.java
src/main/java/io/github/externschool/planner/dto/TeacherDTO.java
src/test/java/io/github/externschool/planner/converter/TeacherConvertersTest.java

#105 remove user from teacher converter

---

src/main/resources/templates/teacher/teacher_list.html

#103 create template to show all teacher profiles

---

src/main/java/io/github/externschool/planner/service/SchoolSubjectService.java
src/main/java/io/github/externschool/planner/service/SchoolSubjectServiceImpl.java
src/main/java/io/github/externschool/planner/service/TeacherServiceImpl.java
src/test/java/io/github/externschool/planner/repository/SchoolSubjectRepositoryIntegrationTest.java
src/test/java/io/github/externschool/planner/service/SchoolSubjectServiceTest.java

Refactor SchoolSubject, Teacher Service, Fix Tests

---

src/main/resources/templates/teacher/teacher_list.html
src/main/resources/templates/teacher/teacher_profile.html

#118 refactor teacher template

---

src/main/resources/templates/fragments/header.html
src/main/resources/templates/greeting.html
src/main/resources/templates/login.html
src/main/resources/templates/signup.html
src/main/resources/templates/success.html
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java

#109 Update Header Template to open Admin console

---

src/main/java/io/github/externschool/planner/config/WebConfig.java
src/main/java/io/github/externschool/planner/converter/LocalDateFormatter.java
src/main/java/io/github/externschool/planner/converter/SchoolSubjectFormatter.java
src/main/java/io/github/externschool/planner/entity/SchoolSubject.java
src/test/java/io/github/externschool/planner/bootstrapdata/BootstrapDataPopulatorTest.java
src/test/java/io/github/externschool/planner/converter/LocalDateFormatterTest.java
src/test/java/io/github/externschool/planner/converter/SchoolSubjectFormatterTest.java
src/test/java/io/github/externschool/planner/converter/TeacherConvertersTest.java
src/test/java/io/github/externschool/planner/service/TeacherServiceTest.java

#135 Create SchoolSubject Formatter, LocalDateFormatter

---

src/main/resources/templates/student/student_list.html

#120 Add Student list template

---

src/main/java/io/github/externschool/planner/config/WebConfig.java
src/main/java/io/github/externschool/planner/converter/StudentDTOToStudent.java
src/main/java/io/github/externschool/planner/converter/StudentToStudentDTO.java
src/main/java/io/github/externschool/planner/dto/StudentDTO.java
src/main/java/io/github/externschool/planner/entity/GradeLevel.java
src/test/java/io/github/externschool/planner/converter/StudentConvertersTest.java

#125 and #128 added StudentDTO and Student-DTO converters.

Added StudentDTO #125 and Student-DTO converters #128.

---

src/main/resources/templates/subject/subject_form.html

An alternative form to the previous simple list
close #148

#148 add subjects and grades combined form

---

src/main/java/io/github/externschool/planner/aop/LogExecutionTime.java
src/main/java/io/github/externschool/planner/aop/LoggingAspect.java
src/main/resources/application.properties

#144 Fix LoggingAspect Formatting

---

src/main/java/io/github/externschool/planner/bootstrapdata/BootstrapDataPopulator.java
src/main/java/io/github/externschool/planner/entity/SchoolSubject.java
src/main/java/io/github/externschool/planner/entity/StudyPlan.java
src/main/resources/application.properties
src/test/java/io/github/externschool/planner/repository/StudyPlanJpaTest.java

#151 Study Plan

---

src/main/java/io/github/externschool/planner/bootstrapdata/BootstrapDataPopulator.java
src/main/java/io/github/externschool/planner/controller/ScheduleController.java
src/main/java/io/github/externschool/planner/dto/ScheduleEventReq.java
src/main/java/io/github/externschool/planner/entity/schedule/ScheduleEventType.java
src/main/java/io/github/externschool/planner/exceptions/UserCannotCreateEventException.java
src/main/java/io/github/externschool/planner/repository/schedule/ScheduleEventTypeRepository.java
src/main/java/io/github/externschool/planner/service/ScheduleEventTypeService.java
src/main/java/io/github/externschool/planner/service/ScheduleEventTypeServiceImpl.java
src/main/java/io/github/externschool/planner/service/ScheduleService.java
src/main/java/io/github/externschool/planner/service/ScheduleServiceImpl.java
src/main/resources/application.properties
src/main/resources/templates/fragments/header.html
src/main/resources/templates/scheduleEvents/formCreateScheduleEvent.html
src/test/java/io/github/externschool/planner/controller/ScheduleControllerTest.java
src/test/java/io/github/externschool/planner/factories/RolesFactory.java
src/test/java/io/github/externschool/planner/factories/schedule/ScheduleEventFactory.java
src/test/java/io/github/externschool/planner/repository/schedule/ScheduleEventTypeRepositoryIntegrationTest.java
src/test/java/io/github/externschool/planner/service/ScheduleEventTypeServiceIntegrationTest.java
src/test/java/io/github/externschool/planner/service/ScheduleEventTypeServiceTest.java
src/test/java/io/github/externschool/planner/service/ScheduleServiceTest.java

82 set skeleton for event service layer

---

src/main/java/io/github/externschool/planner/config/SpringSecurityConfig.java
src/main/java/io/github/externschool/planner/config/WebConfig.java
src/main/java/io/github/externschool/planner/controller/UserController.java
src/main/java/io/github/externschool/planner/converter/UserDTOToUser.java
src/main/java/io/github/externschool/planner/converter/UserToUserDTO.java
src/main/java/io/github/externschool/planner/dto/UserDTO.java
src/main/java/io/github/externschool/planner/entity/User.java
src/main/java/io/github/externschool/planner/service/UserService.java
src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/main/resources/templates/login.html
src/main/resources/templates/signup.html
src/test/java/io/github/externschool/planner/config/SpringSecurityConfigTest.java
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java

#171 Complete User Forms Processing

---

src/main/java/io/github/externschool/planner/config/WebConfig.java
src/main/java/io/github/externschool/planner/controller/UserController.java
src/main/java/io/github/externschool/planner/converter/UserDTOToUser.java
src/main/java/io/github/externschool/planner/converter/UserToUserDTO.java
src/main/java/io/github/externschool/planner/converter/VerificationKeyFormatter.java
src/main/java/io/github/externschool/planner/dto/UserDTO.java
src/main/java/io/github/externschool/planner/entity/Role.java
src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/main/resources/templates/signup.html
src/test/java/io/github/externschool/planner/controller/ScheduleControllerTest.java
src/test/java/io/github/externschool/planner/converter/UserConvertersTest.java
src/test/java/io/github/externschool/planner/service/UserServiceTest.java

#173 Add Missing And Fix Existing Tests

---

src/main/java/io/github/externschool/planner/bootstrapdata/BootstrapDataPopulator.java
src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/controller/UserController.java
src/main/java/io/github/externschool/planner/converter/UserDTOToUser.java
src/main/java/io/github/externschool/planner/converter/UserToUserDTO.java
src/main/java/io/github/externschool/planner/dto/PersonDTO.java
src/main/java/io/github/externschool/planner/service/PersonService.java
src/main/java/io/github/externschool/planner/service/PersonServiceImpl.java
src/main/java/io/github/externschool/planner/service/VerificationKeyServiceImpl.java
src/main/resources/application.properties
src/main/resources/templates/guest/person_profile.html
src/main/resources/templates/login.html
src/main/resources/templates/student/student_profile.html
src/main/resources/templates/teacher/teacher_profile.html
src/test/java/io/github/externschool/planner/config/SpringSecurityConfigTest.java
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java
src/test/java/io/github/externschool/planner/converter/UserConvertersTest.java
src/test/java/io/github/externschool/planner/service/PersonServiceTest.java
src/test/java/io/github/externschool/planner/service/RoleServiceTest.java
src/test/java/io/github/externschool/planner/service/UserServiceTest.java

#163 Fix Guest Controller

---

src/main/java/io/github/externschool/planner/config/WebConfig.java
src/main/java/io/github/externschool/planner/converter/StudentToStudentDTO.java
src/main/java/io/github/externschool/planner/converter/StudyPlanDTOToStudyPlan.java
src/main/java/io/github/externschool/planner/converter/StudyPlanToStudyPlanDTO.java
src/main/java/io/github/externschool/planner/dto/StudyPlanDTO.java
src/main/java/io/github/externschool/planner/entity/StudyPlan.java
src/test/java/io/github/externschool/planner/converter/StudyPlanConverterTest.java

178-studyPlanConverterAdded

---

src/main/java/io/github/externschool/planner/util/Constants.java
src/main/resources/templates/error.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/guest/person_list.html
src/main/resources/templates/guest/person_profile.html
src/main/resources/templates/login.html
src/main/resources/templates/plan/plan_list.html
src/main/resources/templates/signup.html
src/main/resources/templates/student/student_list.html
src/main/resources/templates/student/student_profile.html
src/main/resources/templates/subject/subject_list.html
src/main/resources/templates/teacher/teacher_list.html
src/main/resources/templates/teacher/teacher_profile.html

#186 Translate UI to Ukrainian

---

src/main/java/io/github/externschool/planner/converter/PersonDTOToPerson.java
src/main/java/io/github/externschool/planner/converter/StudentDTOToStudent.java
src/main/java/io/github/externschool/planner/converter/StudentToStudentDTO.java
src/main/java/io/github/externschool/planner/converter/TeacherDTOToTeacher.java
src/main/java/io/github/externschool/planner/converter/TeacherToTeacherDTO.java
src/main/java/io/github/externschool/planner/entity/User.java
src/main/java/io/github/externschool/planner/entity/profile/Person.java
src/main/java/io/github/externschool/planner/service/PersonServiceImpl.java
src/main/java/io/github/externschool/planner/service/StudentServiceImpl.java
src/test/java/io/github/externschool/planner/service/TeacherServiceIntegrationTest.java

#191 Refactor Person Related Objects

---

src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/controller/UserController.java
src/main/java/io/github/externschool/planner/service/UserService.java
src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/main/resources/templates/guest/person_profile.html
src/main/resources/templates/teacher/teacher_list.html
src/main/resources/templates/teacher/teacher_schedule.html
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java
src/test/java/io/github/externschool/planner/service/UserServiceTest.java

#200 Fix Guest Role Assignment

---

src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/controller/UserController.java
src/main/java/io/github/externschool/planner/dto/PersonDTO.java
src/main/java/io/github/externschool/planner/service/UserService.java
src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/main/resources/templates/fragments/header.html
src/main/resources/templates/guest/person_profile.html
src/main/resources/templates/main.html
src/main/resources/templates/student/student_list.html
src/main/resources/templates/teacher/teacher_list.html
src/main/resources/templates/teacher/teacher_profile.html
src/main/resources/templates/teacher/teacher_schedule.html
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/controller/TeacherControllerTest.java
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java
src/test/java/io/github/externschool/planner/service/UserServiceTest.java

#202 Teachers Schedule Template & Controller Skeleton

---

src/main/java/io/github/externschool/planner/bootstrapdata/BootstrapDataPopulator.java
src/main/resources/templates/fragments/header.html
src/main/resources/templates/signup.html
src/main/resources/templates/teacher/teacher_list.html

#204 Translate to Ukrainian Bootstrapped data

---

src/main/java/io/github/externschool/planner/entity/User.java
src/main/java/io/github/externschool/planner/entity/profile/Person.java
src/test/java/io/github/externschool/planner/service/PersonServiceTest.java

#196 Fix Cascade

---

pom.xml
src/main/java/io/github/externschool/planner/emailservice/EmailService.java
src/main/java/io/github/externschool/planner/util/Constants.java
src/main/resources/application.properties
src/test/java/io/github/externschool/planner/emailservice/EmailServiceTest.java

207-email service

---

src/main/java/io/github/externschool/planner/service/SchoolSubjectServiceImpl.java
src/main/java/io/github/externschool/planner/util/CollatorHolder.java
src/test/java/io/github/externschool/planner/service/SchoolSubjectServiceTest.java

fixed non-ascii sorting

---

src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/service/UserService.java
src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/main/java/io/github/externschool/planner/util/Constants.java
src/main/resources/static/js/guestList.js
src/main/resources/templates/guest/guest_list.html
src/main/resources/templates/student/student_list.html
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/service/UserServiceTest.java

#235 Create new guest profiles with fake users

---

src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/service/UserServiceImpl.java

#237 fix minor bug in user delete

---

src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/controller/MainController.java
src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/emailservice/EmailServiceImpl.java
src/main/java/io/github/externschool/planner/service/ScheduleService.java
src/main/java/io/github/externschool/planner/service/ScheduleServiceImpl.java
src/main/java/io/github/externschool/planner/util/Utils.java
src/main/resources/static/js/teacherScheduleModals.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/teacher/teacher_list.html
src/main/resources/templates/teacher/teacher_schedule.html
src/main/resources/templates/teacher/teacher_visitors.html
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/controller/StudentControllerTest.java
src/test/java/io/github/externschool/planner/controller/TeacherControllerTest.java
src/test/java/io/github/externschool/planner/emailservice/EmailServiceTest.java
src/test/java/io/github/externschool/planner/service/ScheduleServiceTest.java
src/test/java/io/github/externschool/planner/util/UtilsTest.java

#241 Implement Search for Guests, Students & Teachers

---

src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/entity/schedule/ScheduleEvent.java
src/main/java/io/github/externschool/planner/service/ScheduleService.java
src/main/java/io/github/externschool/planner/service/ScheduleServiceImpl.java
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/repository/schedule/ParticipantRepositoryTest.java
src/test/java/io/github/externschool/planner/repository/schedule/ScheduleEventRepositoryIntegrationTest.java
src/test/java/io/github/externschool/planner/service/ScheduleServiceTest.java
src/test/java/io/github/externschool/planner/service/UserServiceIntegrationTest.java
src/test/resources/datasets/scheduleEvent/oneEvent.sql

#231 optimistic locking for events

---

src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/dto/PersonDTO.java
src/main/resources/static/js/studentSchedule.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/student/student_list.html
src/main/resources/templates/student/student_schedule.html
src/main/resources/templates/student/student_subscriptions.html
src/main/resources/templates/teacher/teacher_list.html
src/test/java/io/github/externschool/planner/controller/StudentControllerTest.java

#217 processing students subscriptions

---

src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/resources/templates/teacher/teacher_visitors.html

#247 Fix Role assignment when new Student is created

---

pom.xml
src/main/java/io/github/externschool/planner/controller/ScheduleController.java
src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/converter/LocalDateAttributeConverter.java
src/main/java/io/github/externschool/planner/entity/schedule/ScheduleHoliday.java
src/main/java/io/github/externschool/planner/repository/schedule/ScheduleHolidayRepository.java
src/main/java/io/github/externschool/planner/service/ScheduleService.java
src/main/java/io/github/externschool/planner/service/ScheduleServiceImpl.java
src/test/java/io/github/externschool/planner/repository/schedule/ParticipantRepositoryTest.java
src/test/java/io/github/externschool/planner/repository/schedule/ScheduleHolidayRepositoryTest.java
src/test/java/io/github/externschool/planner/service/ScheduleServiceTest.java

#249 New Events Creation with Standard Schema and Holidays

---

src/main/java/io/github/externschool/planner/bootstrapdata/BootstrapDataPopulator.java
src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/controller/ScheduleController.java
src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/entity/schedule/ScheduleEvent.java
src/main/java/io/github/externschool/planner/entity/schedule/ScheduleTemplate.java
src/main/java/io/github/externschool/planner/exceptions/EventTypeCanNotBeDeletedException.java
src/main/java/io/github/externschool/planner/exceptions/UserCanNotHandleEventException.java
src/main/java/io/github/externschool/planner/repository/schedule/ScheduleTemplateRepository.java
src/main/java/io/github/externschool/planner/service/ScheduleEventTypeServiceImpl.java
src/main/java/io/github/externschool/planner/service/ScheduleService.java
src/main/java/io/github/externschool/planner/service/ScheduleServiceImpl.java
src/main/java/io/github/externschool/planner/service/UserServiceImpl.java
src/main/resources/templates/teacher/teacher_schedule.html
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/controller/TeacherControllerTest.java
src/test/java/io/github/externschool/planner/repository/schedule/ScheduleTemplateRepositoryTest.java
src/test/java/io/github/externschool/planner/service/ScheduleEventTypeServiceTest.java
src/test/java/io/github/externschool/planner/service/ScheduleServiceTest.java
src/test/java/io/github/externschool/planner/service/UserServiceTest.java

#253 Refactor Standard Schedule

---

pom.xml
src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/controller/UserController.java
src/main/resources/application.properties
src/main/resources/static/js/teacherScheduleModals.js
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/guest/guest_schedule.html
src/main/resources/templates/login.html
src/main/resources/templates/main.html
src/main/resources/templates/signup.html
src/main/resources/templates/student/student_schedule.html
src/main/resources/templates/teacher/teacher_schedule.html
src/test/java/io/github/externschool/planner/controller/TeacherControllerTest.java

#258 Add Events to Current Weeks Schedule

---

src/main/java/io/github/externschool/planner/config/SpringSecurityConfig.java
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/controller/ScheduleControllerTest.java
src/test/java/io/github/externschool/planner/controller/SchoolSubjectControllerTest.java
src/test/java/io/github/externschool/planner/controller/StudentControllerTest.java
src/test/java/io/github/externschool/planner/controller/StudyPlanControllerTest.java
src/test/java/io/github/externschool/planner/controller/TeacherControllerTest.java
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java

#256 Enable CSRF

---

src/main/java/io/github/externschool/planner/bootstrapdata/BootstrapDataPopulator.java
src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/service/StudyPlanServiceImpl.java
src/main/java/io/github/externschool/planner/util/Constants.java
src/main/resources/static/js/guestSubscriptions.js
src/main/resources/static/js/studentSubscriptions.js
src/main/resources/templates/guest/guest_schedule.html
src/main/resources/templates/guest/guest_subscriptions.html
src/main/resources/templates/student/student_courses.html
src/main/resources/templates/student/student_plan.html
src/main/resources/templates/student/student_schedule.html
src/main/resources/templates/student/student_subscriptions.html
src/main/resources/templates/teacher/teacher_schedule.html
src/main/resources/templates/teacher/teacher_visitors.html
src/test/java/io/github/externschool/planner/controller/TeacherControllerTest.java

#275 update email confirmation hostname

---

src/main/resources/templates/teacher/teacher_schedule.html

#277 Update teacher_schedule.html

---

src/main/java/io/github/externschool/planner/controller/UserController.java
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java

#279 fix user controller sending emails to fake address

---

src/main/java/io/github/externschool/planner/bootstrapdata/BootstrapDataPopulator.java
src/main/java/io/github/externschool/planner/service/ScheduleServiceImpl.java
src/test/java/io/github/externschool/planner/controller/StudentControllerTest.java

#281 fix student controller test

---

src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/controller/UserController.java
src/main/java/io/github/externschool/planner/util/Constants.java
src/main/resources/templates/guest/guest_list.html
src/main/resources/templates/guest/guest_schedule.html
src/main/resources/templates/guest/guest_subscriptions.html
src/main/resources/templates/guest/person_profile.html
src/main/resources/templates/student/student_subscriptions.html
src/test/java/io/github/externschool/planner/controller/GuestControllerTest.java
src/test/java/io/github/externschool/planner/controller/UserControllerTest.java

#284 Fix Titles, Mail message, Subscriptions

---

src/main/java/io/github/externschool/planner/controller/SchoolSubjectController.java
src/main/java/io/github/externschool/planner/util/Constants.java
src/test/java/io/github/externschool/planner/controller/SchoolSubjectControllerTest.java

#286 Block Existing Subjects Name Usage when New Subjects Added

---

pom.xml
src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/resources/templates/error.html
src/main/resources/templates/login.html
src/main/resources/templates/student/student_profile.html
src/main/resources/templates/teacher/teacher_schedule.html
src/main/resources/templates/teacher/teacher_visitors.html
src/test/java/io/github/externschool/planner/controller/TeacherControllerTest.java

#283 Add Visits History

---

src/main/java/io/github/externschool/planner/controller/TeacherController.java
src/main/java/io/github/externschool/planner/util/Constants.java
src/main/resources/templates/main.html
src/main/resources/templates/student/student_profile.html
src/main/resources/templates/teacher/teacher_visitors.html
src/test/java/io/github/externschool/planner/controller/TeacherControllerTest.java

#291 Add Cancelled Events to Visits History. Add Instructions to main page

---

src/main/java/io/github/externschool/planner/controller/StudentController.java
src/main/resources/templates/main.html
src/main/resources/templates/student/student_subscriptions.html
src/main/resources/templates/teacher/teacher_visitors.html

#296 Hide Cancelled Events in Students Schedule

---

src/main/java/io/github/externschool/planner/controller/GuestController.java
src/main/resources/static/css/main.css
src/main/resources/static/js/teacherProfile.js
src/main/resources/templates/event/event_type.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/guest/guest_list.html
src/main/resources/templates/guest/guest_schedule.html
src/main/resources/templates/guest/guest_subscriptions.html
src/main/resources/templates/guest/person_profile.html
src/main/resources/templates/main.html
src/main/resources/templates/plan/plan_list.html
src/main/resources/templates/student/student_list.html
src/main/resources/templates/student/student_plan.html
src/main/resources/templates/student/student_profile.html
src/main/resources/templates/student/student_schedule.html
src/main/resources/templates/student/student_subscriptions.html
src/main/resources/templates/subject/subject_list.html
src/main/resources/templates/teacher/teacher_list.html
src/main/resources/templates/teacher/teacher_profile.html
src/main/resources/templates/teacher/teacher_schedule.html
src/main/resources/templates/teacher/teacher_visitors.html

#298 Refactor UI for Small Devices

---

pom.xml
src/main/java/io/github/externschool/planner/config/SpringSecurityConfig.java
src/main/java/io/github/externschool/planner/config/WebConfig.java
src/main/resources/application.properties
src/main/resources/static/css/main.css
src/main/resources/templates/error.html
src/main/resources/templates/event/event_type.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/guest/guest_list.html
src/main/resources/templates/guest/guest_schedule.html
src/main/resources/templates/guest/guest_subscriptions.html
src/main/resources/templates/guest/person_profile.html
src/main/resources/templates/login.html
src/main/resources/templates/main.html
src/main/resources/templates/plan/plan_list.html
src/main/resources/templates/signup.html
src/main/resources/templates/student/student_courses.html
src/main/resources/templates/student/student_list.html
src/main/resources/templates/student/student_plan.html
src/main/resources/templates/student/student_profile.html
src/main/resources/templates/student/student_schedule.html
src/main/resources/templates/student/student_subscriptions.html
src/main/resources/templates/subject/subject_form.html
src/main/resources/templates/subject/subject_list.html
src/main/resources/templates/success.html
src/main/resources/templates/teacher/teacher_list.html
src/main/resources/templates/teacher/teacher_profile.html
src/main/resources/templates/teacher/teacher_schedule.html
src/main/resources/templates/teacher/teacher_visitors.html
src/test/java/io/github/externschool/planner/util/UtilsTest.java

#273 Refactor js and css libraries import in templates
